<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Djebli Geena">

<title>Single_cell_stade_16_filtrage_fixées</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="sc_16_cell_filtrees_bis_files/libs/clipboard/clipboard.min.js"></script>
<script src="sc_16_cell_filtrees_bis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="sc_16_cell_filtrees_bis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="sc_16_cell_filtrees_bis_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="sc_16_cell_filtrees_bis_files/libs/quarto-html/popper.min.js"></script>
<script src="sc_16_cell_filtrees_bis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="sc_16_cell_filtrees_bis_files/libs/quarto-html/anchor.min.js"></script>
<link href="sc_16_cell_filtrees_bis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="sc_16_cell_filtrees_bis_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="sc_16_cell_filtrees_bis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="sc_16_cell_filtrees_bis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="sc_16_cell_filtrees_bis_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Single_cell_stade_16_filtrage_fixées</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Djebli Geena </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="filtrage-doubletfinder-et-clustering" class="level2">
<h2 class="anchored" data-anchor-id="filtrage-doubletfinder-et-clustering">Filtrage, Doubletfinder et clustering</h2>
<p>Ce pipeline vise à filtrer les données de séquençage d’ARN en <em>single-cell RNA-seq</em> obtenues chez l’oursin au stade <strong>16 cellules fixées du deuxième échantillon</strong>. Les données utilisées sont issues de l’alignement des reads brutes via le pipeline automatisé&nbsp;“<strong>Cell Ranger”</strong>&nbsp;(se référer à la partie Cell Ranger).</p>
<p>Deux jeux de données sont traités ici : le fichier déjà filtré par Cell Ranger et le fichier brut (« raw »). Ce dernier sera filtré manuellement dans ce document afin de comparer nos résultats à ceux fournis par l’outil automatisé. Effectuer son propre filtrage permet de choisir la finnesse des ses filtres, et mieux comprendre ce qui se passe.</p>
</section>
<section id="étape-préliminaire" class="level2">
<h2 class="anchored" data-anchor-id="étape-préliminaire">Étape préliminaire</h2>
<p><strong>Configuration de l’environnement :</strong></p>
<p>Dans un premier temps, il est nécessaire d’installer les packages qui seront utilisés pour l’analyse. Cette installation n’est à effectuer qu’une seule fois sur la machine. Par la suite, il suffira de charger les bibliothèques (libraries) au début de chaque session pour accéder aux outils et fonctions requis.</p>
<ul>
<li><strong>Instalation packages</strong> (à faire qu’une fois) :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Installation des packages si nécessaire</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(c("Seurat", "SeuratObject", "remotes", "clustree")) </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Pour les lancer il faut enlever le "#" devant. </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Seurat &amp; SeuratObject</strong> : il s’agit de bibliothèques de références pour l’analyse de données en Single Cell. Seurat fournit les algorithmes de normalisation, de réduction de dimension (PCA, UMAP) et de clustering. SeuratObject définit la structure de données qui stocke de manière optimisée les matrices d’expression et les métadonnées des cellules.</p>
<p><strong>remotes</strong> : ce package permet d’installer des outils qui ne sont pas encore sur les dépôts officiels (CRAN), mais disponibles directement sur des plateformes comme GitHub.</p>
<p><strong>clustree</strong> : cet outil de visualisation est utilisé pour évaluer la stabilité des clusters. Il permet de construire un “arbre de clustering” afin de visualiser comment les cellules se répartissent entre les différents groupes lorsque l’on fait varier la résolution de l’analyse.</p>
<ul>
<li><strong>Chargement des bibliothèques</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Seurat)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DoubletFinder)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(future)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(clustree)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Analyse Single-Cell et Contrôle Qualité :</strong></p>
<p><strong>Seurat</strong> : L’outil principale utilisé pour l’analyse des données de Single Cell.</p>
<p><strong>DoubletFinder</strong> : Un package qui permet de détecter et exclure les “doublets” (deux cellules capturées dans une seule gouttelette), ce qui évite les artefacts d’expression dans l’analyse.</p>
<p><strong>Manipulation et Calcul :</strong></p>
<p><strong>dplyr</strong> : permet de filtrer les métadonnées ou réorganiser les tableaux de comptage.</p>
<p><strong>future</strong> : utilisé pour activer le calcul en parallèle. Cela permet d’accélérer considérablement les étapes gourmandes en ressources (comme l’analyse de voisinage ou le clustering) en utilisant plusieurs cœurs de votre processeur, purement informatique, pour bien exploiter l’appareil utilisé.</p>
<p><strong>Visualisation et Validation :</strong></p>
<p><strong>ggplot2</strong> : permet de créer des figures sur mesure et de haute qualité.</p>
<p><strong>clustree</strong> : il sert à visualiser la stabilité du partitionnement des cellules selon différentes résolutions. Voir le comportement des clusters.</p>
<ul>
<li><strong>Configuration mémoire</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Augmente la limite de taille de la mémoire pour le calcul parallèle (16 Go)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">future.globals.maxSize =</span> <span class="dv">15000</span> <span class="sc">*</span> <span class="dv">1024</span><span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Utiliser les coeurs disponibles</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Cela permet d'accélérer Seurat </span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plan</span>(<span class="st">"multisession"</span>, <span class="at">workers =</span> parallel<span class="sc">::</span><span class="fu">detectCores</span>() <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="comparaison-des-données-brutes-raw-et-filtrées-filtered" class="level2">
<h2 class="anchored" data-anchor-id="comparaison-des-données-brutes-raw-et-filtrées-filtered">Comparaison des données brutes (raw) et filtrées (filtered)</h2>
<p>Une fois l’environnement de travail configuré pour le traitement et l’analyse, nous procédons à l’importation des jeux de données. L’objectif est de comparer les données brutes aux données filtrées par Cell Ranger afin d’évaluer la qualité initiale de l’échantillon et la pertinence du filtrage automatisé.</p>
<ul>
<li><strong>Importation des données</strong> (brutes et filtrées)</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger les données brutes (Raw)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>raw_data_16f_bis<span class="ot">&lt;-</span> <span class="fu">Read10X</span>(<span class="at">data.dir =</span> <span class="st">"/Users/gege/Desktop/50-1319402224/10_cellranger_multi/urchin_lib2f_out/outs/per_sample_outs/sample4_OB4_F/sample_raw_feature_bc_matrix"</span>)<span class="co"># ici il faut mettre le chemin des fichiers sur l'ordi où est lancé le pipline</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>seurat_raw_16f_bis <span class="ot">&lt;-</span> <span class="fu">CreateSeuratObject</span>(<span class="at">counts =</span> raw_data_16f_bis, <span class="at">project =</span> <span class="st">"Raw_Data_16f_bis"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Charger les données filtrées par Cell Ranger (Filtered)</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>filtered_data_16f_bis <span class="ot">&lt;-</span> <span class="fu">Read10X</span>(<span class="at">data.dir =</span> <span class="st">"/Users/gege/Desktop/50-1319402224/10_cellranger_multi/urchin_lib2f_out/outs/per_sample_outs/sample4_OB4_F/sample_filtered_feature_bc_matrix"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>seurat_filtered_16f_bis <span class="ot">&lt;-</span> <span class="fu">CreateSeuratObject</span>(<span class="at">counts =</span> filtered_data_16f_bis, <span class="at">project =</span> <span class="st">"Filtered_Data_16f_bis"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Raw Feature BC Matrix</strong> : Contient l’intégralité des codes-barres (barcodes) détectés, y compris ceux correspondant à des gouttelettes vides ou contenant uniquement de l’ARN dans le milieu. C’est notre point de départ pour un filtrage personnalisé.</p>
<p><strong>Filtered Feature BC Matrix</strong> : Ce jeu de données a déjà subi le filtrage automatisé de Cell Ranger, qui utilise un algorithme pour ne conserver que les gouttelettes considérées comme de “vraies” cellules.(Se doccumenter dessus pour bien comprendre)</p>
<ul>
<li><strong>Comparaison</strong></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparaison du nombre de cellules :</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>stats_16f_bis <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Type de données"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Brutes (Raw)"</span>, <span class="st">"Filtrées (Cell Ranger)"</span>),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Nombre de Barcodes"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">ncol</span>(seurat_raw_16f_bis), <span class="fu">ncol</span>(seurat_filtered_16f_bis)),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Médiane Gènes/Cellule"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">median</span>(seurat_raw_16f_bis<span class="sc">$</span>nFeature_RNA), <span class="fu">median</span>(seurat_filtered_16f_bis<span class="sc">$</span>nFeature_RNA)),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">check.names =</span> <span class="cn">FALSE</span> </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(stats_16f_bis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Type de données Nombre de Barcodes Médiane Gènes/Cellule
1           Brutes (Raw)             920067                   2.0
2 Filtrées (Cell Ranger)               4196                5216.5</code></pre>
</div>
</div>
<p>L’écart entre les données brutes et les données filtrées par Cell Ranger met en évidence l’importance de l’étape de nettoyage.</p>
<p><strong>Données Brutes (Raw)</strong> : On observe un nombre impressionant de codes-barres (920067). Cependant, la médiane du nombre de gènes par cellule est de 2. Cela indique que l’immense majorité de ces codes-barres correspond à des gouttelettes vides, à des débris cellulaires ou à du bruit de fond ne contenant aucune information biologique exploitable. On choisi la médiane ici, car elle est plus représentative que la moyenne.</p>
<p><strong>Données Filtrées (Cell Ranger)</strong> : Après le filtrage de Cell Ranger, le jeu de données est réduit à 4196 cellules potentielles. Pour ces dernières, la médiane s’élève à 5216.5 gènes par cellule, ce qui témoigne d’une bonne profondeur de séquençage et de la capture de bonnes cellules.</p>
<p>Le pipeline Cell Ranger a éliminé une grande majorité des codes-barres initiaux. Ce filtrage fort est normal : il permet de passer de données immenses et bruitées à un jeu de données exploitable composé uniquement de véritables cellules.</p>
<p>En premier, il faut éliminer le bruit de fond (donné par les billes vides)</p>
</section>
<section id="la-sélection-des-barcodes" class="level2">
<h2 class="anchored" data-anchor-id="la-sélection-des-barcodes">La sélection des barcodes</h2>
<p>Après avoir comparé les données brutes aux résultats de Cell Ranger, nous débutons le processus de filtrage manuel. La première étape commence dans la sélection des codes-barres (barcodes). Cette analyse permet de définir un seuil de coupure afin de distinguer les véritables cellules des gouttelettes vides ou des débris, permettant ainsi un premier filtrage.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Préparation des données</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>counts_bc_16f_bis <span class="ot">&lt;-</span> <span class="fu">sort</span>(seurat_raw_16f_bis<span class="sc">$</span>nCount_RNA, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>df_16f_bis <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">rank =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(counts_bc_16f_bis), <span class="at">counts =</span> counts_bc_16f_bis)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul du seuil de Cell Ranger pour l'affichage, pour voir leur choix. </span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>seuil_cr_16f_bis <span class="ot">&lt;-</span> <span class="fu">min</span>(seurat_filtered_16f_bis<span class="sc">$</span>nCount_RNA)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Tracer le graphe</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_16f_bis, <span class="fu">aes</span>(<span class="at">x =</span> rank, <span class="at">y =</span> counts)) <span class="sc">+</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span><span class="st">"black"</span>,<span class="at">size =</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> seuil_cr_16f_bis, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">10</span>, <span class="at">y =</span> <span class="dv">10000</span>, <span class="at">label =</span> <span class="st">"Cellules intactes"</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">5</span>, <span class="at">y =</span> <span class="dv">10</span>, <span class="at">label =</span> <span class="st">"ARN dans le milieu / Gouttelettes vides"</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">"Seuils"</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Cell Ranger"</span> <span class="ot">=</span> <span class="st">"red"</span>)) <span class="sc">+</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Knee Plot (Données Brutes - 16 cell fixees bis)"</span>, </span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Visualisation de la transition entre les cellules et le bruit de fond"</span>,</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Rang des Barcodes (Log10)"</span>, </span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Nombre d'UMIs (Log10)"</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/selection-barcodes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ce graphique en échelle log-log, appelé&nbsp;<em>Knee Plot</em>, permet de valider la qualité de la capture cellulaire en visualisant la distribution des transcrits. On peut y distinguer trois zones principales :</p>
<ul>
<li><p><strong>Le plateau des cellules intactes (à gauche) :</strong>&nbsp;La courbe commence à un niveau très élevé (autour de 100 000 UMIs, soit 1e+05) et décroît de manière très douce. Cette région représente les cellules qui ont été correctement capturées. Elles sont extrêmement riches en ARN, ce qui indique des cellules de très bonne qualité.</p></li>
<li><p><strong>Le point d’inflexion ou « coude » (Knee) :</strong>&nbsp;On observe une première chute abrupte juste après le rang 1 000 (1e+03), vers 2 000 - 3 000 barcodes. Cette décroissance brutale marque la transition entre le signal spécifique d’une cellule et le bruit de fond. Plus cette chute est raide, meilleure est la résolution de l’expérience.</p></li>
<li><p><strong>La zone de l’ARN ambiant / gouttelettes vides (à droite) :</strong>&nbsp;Après une brève stabilisation dans la zone de transition, la courbe plonge à nouveau vers les valeurs très basses. Il s’agit des gouttelettes vides qui ne capturent que l’ARN extracellulaire flottant dans le milieu, sans intérêt biologique pour l’analyse.</p></li>
</ul>
<p>On remarque que la ligne rouge de coupure générée par Cell Ranger est placée à environ 500 UMIs. Sur ce jeu de données de cellules fixées, l’algorithme a inclus la zone de transition et a coupé juste avant la chute finale vers l’ARN ambiant.</p>
<p>Ainsi, nous pouvons baser nos seuils de filtrage initiaux sur l’observation de ce&nbsp;<em>Knee Plot</em>&nbsp;:</p>
<ul>
<li><p><strong><code>nCount_RNA &gt; 500</code></strong>&nbsp;: on conserve les barcodes présentant au moins 500 molécules d’ARN (alignement avec la ligne rouge).</p></li>
<li><p><strong><code>nFeature_RNA &gt; 300</code></strong>&nbsp;: on ajoute un critère de complexité en conservant uniquement les barcodes exprimant au moins 300 gènes différents.</p></li>
</ul>
</section>
<section id="filtrage-de-qualité" class="level2">
<h2 class="anchored" data-anchor-id="filtrage-de-qualité">Filtrage de qualité</h2>
<p>En nous appuyant sur les seuils définis précédemment, nous procédons au filtrage des données brutes. J’ai choisi d’importer une nouvelle fois le fichier brut afin de conserver une trace intacte des données initiales d’un côté, et de disposer d’un objet de travail que je vais filtrer et transformer tout au long de ce document.</p>
<ul>
<li><strong>Chargement et premier filtrage des données brutes :</strong></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Chargement </span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>data_dir_16f_bis <span class="ot">&lt;-</span> <span class="st">"/Users/gege/Desktop/50-1319402224/10_cellranger_multi/urchin_lib2f_out/outs/per_sample_outs/sample4_OB4_F/sample_raw_feature_bc_matrix"</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>raw.counts_16f_bis <span class="ot">&lt;-</span> <span class="fu">Read10X</span>(<span class="at">data.dir =</span> data_dir_16f_bis)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Création et premier filtre (Barcode Selection)</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">CreateSeuratObject</span>(<span class="at">counts =</span> raw.counts_16f_bis, </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">min.cells =</span> <span class="dv">3</span>, </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">project =</span> <span class="st">"16 cell fixee_bis"</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">subset</span>(seurat_obj_urchin_16f_bis, </span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>                       nCount_RNA <span class="sc">&gt;</span> <span class="dv">500</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><strong>Nombre de cellules gardées et médianne :</strong></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># On regarde le nombre de cellules gardées après ce premier filtre : </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>stats_16f_bis_1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Type de données"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Brutes (Raw) premier filtrage"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Nombre de Barcodes"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">ncol</span>(seurat_obj_urchin_16f_bis)),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Médiane Gènes/Cellule"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">median</span>(seurat_obj_urchin_16f_bis<span class="sc">$</span>nFeature_RNA) )))</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(stats_16f_bis_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                    Type.de.données
                      Brutes (Raw) premier filtrage
Nombre de Barcodes                            12816
Médiane Gènes/Cellule                           606</code></pre>
</div>
</div>
<p>Nous observeons une amélioration significative par rapport aux données brutes initiales. En effet, nous sommes passés de 920067 à 12154 codes-barres, avec une médiane de 629 gènes par cellule. Ce résultat démontre l’efficacité de la sélection des codes-barres et nous rapproche de notre objectif.</p>
<p>Nous passons désormais à une étape importante : l’analyse du pourcentage d’ARN mitochondrial par cellule.</p>
<ul>
<li><strong>Contrôle du taux d’ARN mitochondrial</strong> (viabilité des cellules) :</li>
</ul>
<p>En biologie cellulaire, un taux élevé d’ARN mitochondrial est souvent un indicateur de mauvaise viabilité. En effet, lorsque la membrane cytoplasmique d’une cellule est endommagée (lyse ou apoptose), l’ARN messager (ARNm) contenu dans le cytoplasme s’échappe. En revanche, les transcrits mitochondriaux, protégés par la double membrane de la mitochondrie, sont retenus plus longtemps ou cellule en stress du lors de la préparation des cellules par exemple.</p>
<p>Si ce pourcentage est trop élevé (généralement supérieur à 5 % ou 10 %), cela signifie que la cellule est probablement morte ou mourante. Ces cellules doivent être exclues de l’analyse, car elles risqueraient de créer des artefacts lors du clustering et de fausser l’interprétation biologique.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># On rajoute le pourcentage mitochondriale</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis[[<span class="st">"percent.mt"</span>]] <span class="ot">&lt;-</span> <span class="fu">PercentageFeatureSet</span>(seurat_obj_urchin_16f_bis, <span class="at">pattern =</span> <span class="st">"^Mt"</span>) </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># On affiche le pourcentage maximal dans nos cellules. </span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(seurat_obj_urchin_16f_bis<span class="sc">$</span>percent.mt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8333333</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(seurat_obj_urchin_16f_bis<span class="sc">$</span>percent.mt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Nous avons calculé le pourcentage d’ARN mitochondrial pour chaque cellule afin d’évaluer leur état de santé. En examinant la valeur maximale obtenue via la fonction max(), nous constatons que le taux le plus élevé n’atteint que 0.8333333 %.</p>
<p>Ce résultat est nettement inférieur au seuil critique de 5 %. Cela indique que l’intégralité des cellules sélectionnées est de très bonne qualité et qu’aucune lyse cellulaire significative n’est à déplorer dans cet échantillon filtré.</p>
<p>Et le pourcantage minimum est de 0%</p>
<p>Maintenant nous allons regarder comment se comportent nos données pour venir affiner notre filtrage.</p>
<ul>
<li><strong>Visualisation de nos données :</strong></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VlnPlot</span>(seurat_obj_urchin_16f_bis, <span class="at">features =</span> <span class="fu">c</span>(<span class="st">"nFeature_RNA"</span>, <span class="st">"nCount_RNA"</span>, <span class="st">"percent.mt"</span>), <span class="at">ncol =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/data-visualisation-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Le VlnPlot permet de visualiser le contrôle qualité avant filtrage. Il montre la distribution de trois métriques clés (<code>nFeature_RNA</code>,&nbsp;<code>nCount_RNA</code>&nbsp;et&nbsp;<code>percent.mt</code>) pour l’ensemble des gouttelettes capturées.</p>
<ul>
<li><p><strong><code>nFeature_RNA</code>&nbsp;(Complexité) :</strong>&nbsp;Il s’agit du nombre de gènes différents détectés par barcode, représentant la richesse du transcriptome. Loin d’être homogène, la distribution est très étalée. On observe une forte densité à la base du graphique (les gouttelettes vides ou débris de faible complexité), tandis que le signal des véritables cellules s’étire largement vers le haut. Quelques évènements extrêmes dépassent les 6 000 à 7 000 gènes ; il s’agit très probablement de doublets (plusieurs cellules encapsulées dans une même gouttelette) qu’il faudra exclure.</p></li>
<li><p><strong><code>nCount_RNA</code>&nbsp;(Quantité) :</strong>&nbsp;C’est le nombre total de molécules d’ARN (UMIs) par barcode, indiquant la profondeur de capture. Ici encore, la distribution est extrêmement large, atteignant plus de 100 000 UMIs pour les points les plus hauts (une abondance caractéristique des blastomères précoces gorgés d’ARN maternels). Tout comme pour les gènes, la masse concentrée près de zéro représente le bruit de fond. Les valeurs extrêmes au sommet supérieur confirment la présence de doublets.</p></li>
<li><p><strong><code>percent.mt</code>&nbsp;(Viabilité / Qualité de fixation) :</strong>&nbsp;Il indique le pourcentage de transcrits mitochondriaux. C’est le graphique le plus “propre” des trois. L’échelle maximale visible est de 1.00 %, et l’immense majorité des points se situe très en dessous de 0.50 %. Ce taux extrêmement faible confirme que les cellules n’ont pas souffert de lyse ou de stress majeur, validant l’excellente qualité de la préparation et de la fixation.</p></li>
<li><p><strong>Filtrage de qualité optimisé</strong> :</p></li>
</ul>
<p>L’objectif est de ne conserver que les cellules présentant superieure à 2000 gènes, seuils basés sur ce que nous avons observés plus haut. Pour le contrôle mitochondrial, nous avons choisi un seuil de 0.9 %.</p>
<p>Ce choix se justifie par la qualité globale de l’échantillon : le taux maximal observé étant de 0.83 %, un seuil à 0.9 % permet d’exclure tout début de dégradation cellulaire tout en conservant l’intégralité des cellules saines. Cette étape n’est pas obligatoire mais il est plus sûr de la faire.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">subset</span>(seurat_obj_urchin_16f_bis, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">subset =</span> nFeature_RNA <span class="sc">&gt;</span> <span class="dv">2000</span> <span class="sc">&amp;</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                               nCount_RNA <span class="sc">&gt;</span> <span class="dv">20000</span> <span class="sc">&amp;</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                              percent.mt <span class="sc">&lt;</span> <span class="fl">0.9</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">VlnPlot</span>(seurat_obj_urchin_16f_bis, <span class="at">features =</span> <span class="fu">c</span>(<span class="st">"nFeature_RNA"</span>, <span class="st">"nCount_RNA"</span>, <span class="st">"percent.mt"</span>), <span class="at">ncol =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/data-filter-strict-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Le résultat du filtrage montre une distribution des métriques de qualité beaucoup plus homogène. En appliquant nos seuils de sélection, notamment en conservant un nombre de gènes superieur à 2 000 et en plafonnant le taux mitochondrial à un niveau extrêmement bas (inférieur à 0.9%), nous avons nettoyé le jeu de données de son bruit de fond. Ces données, désormais débarrassées des débris et des cellules en souffrance, constituent une base très solide pour l’étape de détection des doublets qui peuvent être restés.</p>
<ul>
<li><strong>Nombre de cellules gardées et médianne :</strong></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># On regarde le nombre de cellules gardées après ce deuxième filtrage : </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>stats_16f_bis_2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Type de données"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Filtrées optimisées"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Nombre de Barcodes"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">ncol</span>(seurat_obj_urchin_16f_bis)),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Médiane Gènes/Cellule"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">median</span>(seurat_obj_urchin_16f_bis<span class="sc">$</span>nFeature_RNA) )))</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(stats_16f_bis_2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Type.de.données
                      Filtrées optimisées
Nombre de Barcodes                   2541
Médiane Gènes/Cellule                5793</code></pre>
</div>
</div>
</section>
<section id="normalisation-réduction-de-dimension-et-clustering" class="level2">
<h2 class="anchored" data-anchor-id="normalisation-réduction-de-dimension-et-clustering">Normalisation, réduction de dimension et clustering</h2>
<ul>
<li><strong>Normalisation</strong></li>
</ul>
<p>Ici nous normalisons avant l’étape Doubletfinder car il crée des “cellules artificielles” en mélangeant les profils d’expression de nos vraies cellules. Pour que ce mélange mathématique fonctionne, il faut que toutes les cellules soient sur la même échelle de mesure, d’où l’interêt de la normalisation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SCTransform fait tout : Normalisation, Scaling et sélection des gènes variables </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># On précise variable.features.n = 3000 </span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">SCTransform</span>(seurat_obj_urchin_16f_bis, </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">method =</span> <span class="st">"glmGamPoi"</span>, </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">variable.features.n =</span> <span class="dv">2000</span>, </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="co">#On lance la PCA directement après</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">RunPCA</span>(seurat_obj_urchin_16f_bis, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>SCTransform</strong> : est une méthode qui utilise un modèle de régression (Gamma-Poisson) pour stabiliser la variance et corriger les effets de profondeur de séquençage. Elle offre une meilleure définition des gènes hautement variables (ici, les 2 000 gènes les plus informatifs) par rapport aux méthodes de normalisation logarithmiques classiques. Cette étape est importante pour la réduction de dimension (PCA) et la détection des doublets.</p>
<p><strong>PCA</strong> : l’analyse en composantes principales permet de réduire la complexité de milliers de gène en quelques axes mathématiques (les PC), en général les premières composantes capturent les variations biologiques les plus fortes.</p>
<p>Une fois la normalisation par SCTransform effectuée, nous avons réalisé une Analyse en Composantes Principales (PCA). L’objectif est maintenant d’identifier les composantes principales (PC) qui expliquent le mieux la variance observée dans nos données. Déterminer le nombre optimal de PC est donc essentiel pour que DoubletFinder puisse comparer efficacement les vraies cellules aux doublets simulés.</p>
<ul>
<li><strong>Réduction de dimension</strong></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># On visualise quels sont les axes qui explique le plus la variance : </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ElbowPlot</span>(seurat_obj_urchin_16f_bis) <span class="sc">+</span> </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"PC (Composantes Principales)"</span>, </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Écart-type (Standard Deviation)"</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Détermination du nombre de PC (Elbow Plot) 16 cell fixées bis"</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/composantes-principales-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># On voit qu'on a un coude au niveau de 5-10</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># On garde les 10 premiers axes mais selon ce qu'on va observé avec les clusters par la suite on pourrait baisser le nombre de PC (À 7 par exemple)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>L’examen de l’Elbow Plot révèle un coude situé entre les PC 5 et 10. Pour la suite de l’analyse, nous choisissons de conserver les 10 premières composantes principales, car elles capturent l’essentiel de la structure biologique de l’échantillon. Il sera toutefois intéressant, lors des étapes de clustering, de tester différentes résolutions et un nombre d’axes réduit afin d’observer la stabilité des clusters.</p>
<ul>
<li><strong>Clustering et UMAP</strong></li>
</ul>
<p>Afin d’optimiser la détection par DoubletFinder, nous allons réaliser une première réduction de dimension (UMAP) et un clustering préliminaire. Le clustering est nécessaire car l’algorithme s’appuie sur la structure locale des données et les identités des clusters pour modéliser les doublets artificiels. La UMAP n’a pas d’intérêt, à part juste une première visualisation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">RunUMAP</span>(seurat_obj_urchin_16f_bis, <span class="at">dims =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">FindNeighbors</span>(seurat_obj_urchin_16f_bis, <span class="at">dims =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">FindClusters</span>(seurat_obj_urchin_16f_bis, <span class="at">resolution =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 2541
Number of edges: 81411

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.7925
Number of communities: 6
Elapsed time: 0 seconds</code></pre>
</div>
</div>
<p><strong>RunUMAP</strong> : Cette fonction génère une projection non linéaire en 2D de nos 10 composantes principales. L’UMAP permet de visualiser la proximité entre les cellules : plus deux points sont proches sur le graphique, plus leur profil d’expression génique est similaire.</p>
<p><strong>FindNeighbors</strong> : Calcule un graphe de voisinage. Pour chaque cellule, l’algorithme cherche ses “voisins” les plus proches dans l’espace de la PCA. C’est la base mathématique nécessaire au partitionnement des données.</p>
<p><strong>FindClusters</strong> : C’est l’étape de regroupement proprement dite. Nous utilisons ici une résolution de 0,5, qui est une valeur standard pour un jeu de données de cette taille,c’est une valeur par défaut mais nous nous y interresserons de plus prêt plus tard.</p>
<p>Ce clustering est temporaire, mais nous voyons que nous avons 6 clusters préliminaires.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">DimPlot</span>(seurat_obj_urchin_16f_bis, <span class="at">reduction =</span> <span class="st">"umap"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"UMAP préliminaire (avant DoubletFinder) 16 cell fixées bis"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/UMAP-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Maintenant que nos clusters préliminaires sont définis, nous pouvons préparer l’exécution de DoubletFinder. Une étape importante avant le lancement de l’algorithme est le calcul de la proportion homotypique.</p>
</section>
<section id="calcul-de-la-proportion-homotypique-et-des-paramètres-de-doubletfinder" class="level2">
<h2 class="anchored" data-anchor-id="calcul-de-la-proportion-homotypique-et-des-paramètres-de-doubletfinder">Calcul de la proportion homotypique et des paramètres de DoubletFinder</h2>
<p>Les doublets homotypiques correspondent à la fusion de deux cellules de même type (provenant du même cluster). Ces doublets sont biologiquement moins gênants car ils ne créent pas de “faux” types cellulaires, contrairement aux doublets hétérotypiques (mélange de deux types différents). En estimant cette proportion, nous pouvons affiner le nombre attendu de doublets à exclure pour ne cibler que les plus problématiques.</p>
<ul>
<li><strong>Proportion homotypique</strong>:</li>
</ul>
<p>https://cdn.10xgenomics.com/image/upload/v1722285481/support-documents/CG000315_ChromiumNextGEMSingleCell3__GeneExpression_v3.1_DualIndex__RevF.pdf</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul de la proportion homotypique basée sur les clusters (résolution 0.5)</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Cela estime la probabilité que deux cellules d'un doublet viennent du même cluster.</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>homotypic.prop_16f_bis <span class="ot">&lt;-</span> <span class="fu">modelHomotypic</span>(seurat_obj_urchin_16f_bis<span class="sc">@</span>active.ident) </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Définition du taux de multiplets attendu </span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co"># La règle générale, basée sur la documentation officielle de 10x Genomics, est une augmentation d'environ 0,8 % du taux de multiplets par tranche de 1 000 cellules récupérées (soit environ 0,000008 par cellule). Ici on a 1206 cellules donc : 2541 * 0.000008 = 0.020328</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>expected_rate_16f_bis <span class="ot">&lt;-</span> <span class="fl">0.020</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>nExp_poi_16f_bis <span class="ot">&lt;-</span> <span class="fu">round</span>(expected_rate_16f_bis <span class="sc">*</span> <span class="fu">ncol</span>(seurat_obj_urchin_16f_bis)) </span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>nExp_poi_16f_bis</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustement du nombre final de doublets à détecter</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># On retire les doublets homotypiques car ils sont indifférenciables des singlets au niveau de l'expression génique.</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>nExp_final_16f_bis <span class="ot">&lt;-</span> <span class="fu">round</span>(nExp_poi_16f_bis <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> homotypic.prop_16f_bis))</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>nExp_final_16f_bis</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 41</code></pre>
</div>
</div>
<p>La comparaison entre le nombre théorique de doublets attendus 51 et le nombre final calculé après ajustement homotypique 41 montre une cohérence. Cette légère différence s’explique par le fait que nous avons soustrait les doublets dits « homotypiques ». Comme ces doublets sont formés par deux cellules de même type, leur profil d’expression reste propre et ne crée pas de faux clusters. En ciblant uniquement les 41 doublets hétérotypiques, nous nous concentrons sur les artefacts qui pourraient fausser l’identification des lignages cellulaires.</p>
<p>La prochaine étape consiste à calibrer les paramètres de l’algorithme DoubletFinder</p>
<ul>
<li><strong>Définition des paramètres de DoubletFinder</strong></li>
</ul>
<p>L’objectif est d’identifier précisément les “doublets” (deux cellules capturées dans une seule gouttelette) qui subsistent dans notre échantillon.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">future.globals.maxSize =</span> <span class="dv">15000</span> <span class="sc">*</span> <span class="dv">1024</span><span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plan</span>(<span class="st">"sequential"</span>) <span class="co"># Désactive le multi-cœur pour économiser la RAM physique</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co">#j'ai rajouté cette étape car mon ordinateur avait du mal a faire le travail </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulation des doublets et balayage des paramètres :</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># On utilise les 10 PC</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>sweep.res.list_16f_bis <span class="ot">&lt;-</span> <span class="fu">paramSweep</span>(seurat_obj_urchin_16f_bis, <span class="at">PCs =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">sct =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Creating artificial doublets for pN = 5%"
[1] "Creating Seurat object..."
[1] "Running SCTransform..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Running PCA..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Calculating PC distance matrix..."
[1] "Defining neighborhoods..."
[1] "Computing pANN across all pK..."
[1] "pK = 0.005..."
[1] "pK = 0.01..."
[1] "pK = 0.02..."
[1] "pK = 0.03..."
[1] "pK = 0.04..."
[1] "pK = 0.05..."
[1] "pK = 0.06..."
[1] "pK = 0.07..."
[1] "pK = 0.08..."
[1] "pK = 0.09..."
[1] "pK = 0.1..."
[1] "pK = 0.11..."
[1] "pK = 0.12..."
[1] "pK = 0.13..."
[1] "pK = 0.14..."
[1] "pK = 0.15..."
[1] "pK = 0.16..."
[1] "pK = 0.17..."
[1] "pK = 0.18..."
[1] "pK = 0.19..."
[1] "pK = 0.2..."
[1] "pK = 0.21..."
[1] "pK = 0.22..."
[1] "pK = 0.23..."
[1] "pK = 0.24..."
[1] "pK = 0.25..."
[1] "pK = 0.26..."
[1] "pK = 0.27..."
[1] "pK = 0.28..."
[1] "pK = 0.29..."
[1] "pK = 0.3..."
[1] "Creating artificial doublets for pN = 10%"
[1] "Creating Seurat object..."
[1] "Running SCTransform..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Running PCA..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Calculating PC distance matrix..."
[1] "Defining neighborhoods..."
[1] "Computing pANN across all pK..."
[1] "pK = 0.005..."
[1] "pK = 0.01..."
[1] "pK = 0.02..."
[1] "pK = 0.03..."
[1] "pK = 0.04..."
[1] "pK = 0.05..."
[1] "pK = 0.06..."
[1] "pK = 0.07..."
[1] "pK = 0.08..."
[1] "pK = 0.09..."
[1] "pK = 0.1..."
[1] "pK = 0.11..."
[1] "pK = 0.12..."
[1] "pK = 0.13..."
[1] "pK = 0.14..."
[1] "pK = 0.15..."
[1] "pK = 0.16..."
[1] "pK = 0.17..."
[1] "pK = 0.18..."
[1] "pK = 0.19..."
[1] "pK = 0.2..."
[1] "pK = 0.21..."
[1] "pK = 0.22..."
[1] "pK = 0.23..."
[1] "pK = 0.24..."
[1] "pK = 0.25..."
[1] "pK = 0.26..."
[1] "pK = 0.27..."
[1] "pK = 0.28..."
[1] "pK = 0.29..."
[1] "pK = 0.3..."
[1] "Creating artificial doublets for pN = 15%"
[1] "Creating Seurat object..."
[1] "Running SCTransform..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Running PCA..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Calculating PC distance matrix..."
[1] "Defining neighborhoods..."
[1] "Computing pANN across all pK..."
[1] "pK = 0.005..."
[1] "pK = 0.01..."
[1] "pK = 0.02..."
[1] "pK = 0.03..."
[1] "pK = 0.04..."
[1] "pK = 0.05..."
[1] "pK = 0.06..."
[1] "pK = 0.07..."
[1] "pK = 0.08..."
[1] "pK = 0.09..."
[1] "pK = 0.1..."
[1] "pK = 0.11..."
[1] "pK = 0.12..."
[1] "pK = 0.13..."
[1] "pK = 0.14..."
[1] "pK = 0.15..."
[1] "pK = 0.16..."
[1] "pK = 0.17..."
[1] "pK = 0.18..."
[1] "pK = 0.19..."
[1] "pK = 0.2..."
[1] "pK = 0.21..."
[1] "pK = 0.22..."
[1] "pK = 0.23..."
[1] "pK = 0.24..."
[1] "pK = 0.25..."
[1] "pK = 0.26..."
[1] "pK = 0.27..."
[1] "pK = 0.28..."
[1] "pK = 0.29..."
[1] "pK = 0.3..."
[1] "Creating artificial doublets for pN = 20%"
[1] "Creating Seurat object..."
[1] "Running SCTransform..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Running PCA..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Calculating PC distance matrix..."
[1] "Defining neighborhoods..."
[1] "Computing pANN across all pK..."
[1] "pK = 0.005..."
[1] "pK = 0.01..."
[1] "pK = 0.02..."
[1] "pK = 0.03..."
[1] "pK = 0.04..."
[1] "pK = 0.05..."
[1] "pK = 0.06..."
[1] "pK = 0.07..."
[1] "pK = 0.08..."
[1] "pK = 0.09..."
[1] "pK = 0.1..."
[1] "pK = 0.11..."
[1] "pK = 0.12..."
[1] "pK = 0.13..."
[1] "pK = 0.14..."
[1] "pK = 0.15..."
[1] "pK = 0.16..."
[1] "pK = 0.17..."
[1] "pK = 0.18..."
[1] "pK = 0.19..."
[1] "pK = 0.2..."
[1] "pK = 0.21..."
[1] "pK = 0.22..."
[1] "pK = 0.23..."
[1] "pK = 0.24..."
[1] "pK = 0.25..."
[1] "pK = 0.26..."
[1] "pK = 0.27..."
[1] "pK = 0.28..."
[1] "pK = 0.29..."
[1] "pK = 0.3..."
[1] "Creating artificial doublets for pN = 25%"
[1] "Creating Seurat object..."
[1] "Running SCTransform..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Running PCA..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Calculating PC distance matrix..."
[1] "Defining neighborhoods..."
[1] "Computing pANN across all pK..."
[1] "pK = 0.005..."
[1] "pK = 0.01..."
[1] "pK = 0.02..."
[1] "pK = 0.03..."
[1] "pK = 0.04..."
[1] "pK = 0.05..."
[1] "pK = 0.06..."
[1] "pK = 0.07..."
[1] "pK = 0.08..."
[1] "pK = 0.09..."
[1] "pK = 0.1..."
[1] "pK = 0.11..."
[1] "pK = 0.12..."
[1] "pK = 0.13..."
[1] "pK = 0.14..."
[1] "pK = 0.15..."
[1] "pK = 0.16..."
[1] "pK = 0.17..."
[1] "pK = 0.18..."
[1] "pK = 0.19..."
[1] "pK = 0.2..."
[1] "pK = 0.21..."
[1] "pK = 0.22..."
[1] "pK = 0.23..."
[1] "pK = 0.24..."
[1] "pK = 0.25..."
[1] "pK = 0.26..."
[1] "pK = 0.27..."
[1] "pK = 0.28..."
[1] "pK = 0.29..."
[1] "pK = 0.3..."
[1] "Creating artificial doublets for pN = 30%"
[1] "Creating Seurat object..."
[1] "Running SCTransform..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Running PCA..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Calculating PC distance matrix..."
[1] "Defining neighborhoods..."
[1] "Computing pANN across all pK..."
[1] "pK = 0.005..."
[1] "pK = 0.01..."
[1] "pK = 0.02..."
[1] "pK = 0.03..."
[1] "pK = 0.04..."
[1] "pK = 0.05..."
[1] "pK = 0.06..."
[1] "pK = 0.07..."
[1] "pK = 0.08..."
[1] "pK = 0.09..."
[1] "pK = 0.1..."
[1] "pK = 0.11..."
[1] "pK = 0.12..."
[1] "pK = 0.13..."
[1] "pK = 0.14..."
[1] "pK = 0.15..."
[1] "pK = 0.16..."
[1] "pK = 0.17..."
[1] "pK = 0.18..."
[1] "pK = 0.19..."
[1] "pK = 0.2..."
[1] "pK = 0.21..."
[1] "pK = 0.22..."
[1] "pK = 0.23..."
[1] "pK = 0.24..."
[1] "pK = 0.25..."
[1] "pK = 0.26..."
[1] "pK = 0.27..."
[1] "pK = 0.28..."
[1] "pK = 0.29..."
[1] "pK = 0.3..."</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Résumé des statistiques du balayage</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>sweep.stats_16f_bis <span class="ot">&lt;-</span> <span class="fu">summarizeSweep</span>(sweep.res.list_16f_bis, <span class="at">GT =</span> <span class="cn">FALSE</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul du pK optimal, réglage du filet</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>bcmvn_16f_bis <span class="ot">&lt;-</span> <span class="fu">find.pK</span>(sweep.stats_16f_bis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/parametres-doubletfinder-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
</div>
<p>Pour finaliser la configuration de DoubletFinder, nous avons analysé la distribution du coefficient de bimodalité (BCmetric) en fonction du paramètre pK. Le graphique présente un pic distinct, identifiant la valeur de pK pour laquelle la séparation entre les singlets et les doublets artificiels est maximale.</p>
<p>L’utilisation de ce pK optimal permet d’ajuster la sensibilité du filet de détection, garantissant ainsi que les 41 doublets identifiés précédemment correspondent à des artefacts réels et non à une variation biologique naturelle.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extraction du pK optimal</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>pK_opt_16f_bis <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(bcmvn_16f_bis<span class="sc">$</span>pK[<span class="fu">which.max</span>(bcmvn_16f_bis<span class="sc">$</span>BCmetric)]))</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Le pK optimal identifié est :"</span>, pK_opt_16f_bis))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Le pK optimal identifié est : 0.04"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Le paramètre pK représente la "finesse" ou le voisinage (PC neighborhood size) utilisé pour cette comparaison.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="doubletfinder" class="level2">
<h2 class="anchored" data-anchor-id="doubletfinder">DoubletFinder</h2>
<p>Le paramètrage de doubletfinder fait, nous pouvons lancer la detection des doublets.</p>
<ul>
<li><strong>Detection des doublets</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># On s'assure que l'objet est bien préparé</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">doubletFinder</span>(</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">seu =</span> seurat_obj_urchin_16f_bis, </span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">PCs =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, </span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pN =</span> <span class="fl">0.25</span>, </span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">pK =</span> pK_opt_16f_bis,        <span class="co"># On utilise la valeur optimale du graphique</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">nExp =</span> nExp_final_16f_bis, </span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">sct =</span> <span class="cn">TRUE</span>          <span class="co"># Indispensable avec SCTransform</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Creating 847 artificial doublets..."
[1] "Creating Seurat object..."
[1] "Running SCTransform..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Running PCA..."</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Calculating PC distance matrix..."
[1] "Computing pANN..."
[1] "Classifying doublets.."</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>class_col_16f_bis <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">"DF.classifications"</span>, <span class="fu">colnames</span>(seurat_obj_urchin_16f_bis<span class="sc">@</span>meta.data), <span class="at">value =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Vérification des colonnes</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="fu">paste</span>(<span class="st">"Doublets identifiés dans la colonne :"</span>, class_col_16f_bis))</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(class_col_16f_bis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "DF.classifications_0.25_0.04_41"</code></pre>
</div>
</div>
<p>Nous avons exécuté l’algorithme DoubletFinder en utilisant le pK optimal identifié précédemment. Cette étape compare chaque cellule réelle à des doublets artificiels générés par simulation.</p>
<p>L’algorithme a indiqué les 91 cellules comme étant des doublets hétérotypiques. Cela nous permettra, dans l’étape suivante, de visualiser la localisation de ces doublets sur notre UMAP avant de procéder à leur élimination définitive.</p>
<ul>
<li><strong>Visualisation des doublets</strong></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualisation :On affiche les doublets détectés en rouge sur l'UMAP.</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">DimPlot</span>(seurat_obj_urchin_16f_bis, <span class="at">group.by =</span> class_col_16f_bis, <span class="at">cols =</span> <span class="fu">c</span>(<span class="st">"Singlet"</span> <span class="ot">=</span> <span class="st">"black"</span>, <span class="st">"Doublet"</span> <span class="ot">=</span> <span class="st">"red"</span>)) <span class="sc">+</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Doublets identifiés (en rouge) 16 cellules bis"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/visualisation-des-doublets-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>L’affichage de la projection UMAP permet de confirmer la pertinence de l’identification. La détection étant validée, nous procédons désormais à la suppression définitive de ces doublets pour ne conserver que les singlets (cellules uniques) pour la suite de l’analyse. La suppression de ces 91 cellules n’est pas une perte, mais un gain de précision.</p>
<ul>
<li><strong>Suppression des doublets</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppression définitive des doublets pour ne garder que les "Singlets" (vraies cellules).</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">subset</span>(seurat_obj_urchin_16f_bis, <span class="at">subset =</span> <span class="sc">!!</span><span class="fu">sym</span>(class_col_16f_bis) <span class="sc">==</span> <span class="st">"Singlet"</span>)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">DimPlot</span>(seurat_obj_urchin_16f_bis, <span class="at">group.by =</span> class_col_16f_bis, <span class="at">cols =</span> <span class="fu">c</span>(<span class="st">"Singlet"</span> <span class="ot">=</span> <span class="st">"black"</span>, <span class="st">"Doublet"</span> <span class="ot">=</span> <span class="st">"red"</span>)) <span class="sc">+</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Doublets identifiés (en rouge)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/suppression-des-doublets-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Une fois l’étape de suppression des doublets réalisée, nous pouvons passer au clustering final de nos cellules. Toutefois, avant de fixer un nombre définitif de cluster, nous allons explorer différentes résolutions pour identifier la plus optimale. Cette démarche nous permettra de choisir le niveau le plus stable et le plus cohérent d’un point de vue biologique.</p>
</section>
<section id="analyse-de-la-résolution-et-arbre-de-clustering" class="level2">
<h2 class="anchored" data-anchor-id="analyse-de-la-résolution-et-arbre-de-clustering">Analyse de la résolution et arbre de clustering</h2>
<p>Avant de fixer une partition définitive des populations cellulaires, nous testons différentes résolutions allant de 0,1 à 1,0 avec un pas de 0,1.</p>
<p>L’objectif est de déterminer quelle résolution reflète le mieux la réalité biologique. Une résolution trop faible masquerait la diversité des types cellulaires (sous-clustering), tandis qu’une résolution trop élevée pourrait diviser artificiellement des populations homogènes en créant des clusters sans signification biologique (sur-clustering). L’utilisation d’un arbre de clustering (clustree) nous permettra d’observer la stabilité de ces divisions.</p>
<ul>
<li><strong>Test de résolution</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>res_to_test_16f_bis <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">FindClusters</span>(seurat_obj_urchin_16f_bis, <span class="at">resolution =</span> res_to_test_16f_bis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 2500
Number of edges: 79048

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.9076
Number of communities: 2
Elapsed time: 0 seconds
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 2500
Number of edges: 79048

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.8683
Number of communities: 4
Elapsed time: 0 seconds
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 2500
Number of edges: 79048

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.8413
Number of communities: 5
Elapsed time: 0 seconds
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 2500
Number of edges: 79048

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.8150
Number of communities: 6
Elapsed time: 0 seconds
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 2500
Number of edges: 79048

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.7951
Number of communities: 6
Elapsed time: 0 seconds
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 2500
Number of edges: 79048

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.7761
Number of communities: 7
Elapsed time: 0 seconds
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 2500
Number of edges: 79048

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.7613
Number of communities: 7
Elapsed time: 0 seconds
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 2500
Number of edges: 79048

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.7465
Number of communities: 9
Elapsed time: 0 seconds
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 2500
Number of edges: 79048

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.7346
Number of communities: 12
Elapsed time: 0 seconds
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 2500
Number of edges: 79048

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.7231
Number of communities: 11
Elapsed time: 0 seconds</code></pre>
</div>
</div>
<ul>
<li><strong>Arbre de clustering</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Arbre de clustering</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">clustree</span>(seurat_obj_urchin_16f_bis, <span class="at">prefix =</span> <span class="st">"SCT_snn_res."</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/clustering-tree-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Flèches</strong> : les flèches droites indiquent que les clusters sont bien définis et que les cellules ne sautent pas d’un groupe à l’autre.</p>
<p>Notre jeu de données semble très robuste. Les populations cellulaires sont distinctes et ne se mélangent pas, même quand nous augmentons la résolution.</p>
<p><em>À basse résolution (0.1 à 0.3)</em> : On voit le cluster rouge (0) se diviser en trois (0, 1, 3 en orange). 3 Feuillets embryonnaires ?</p>
<p><em>À haute résolution (0.7 à 1.0)</em> : On commence à voir des flèches qui se croisent, notamment sur la gauche (entre les clusters bleus et violets). C’est le signe que l’algorithme essaie de diviser des populations qui sont très proches biologiquement.</p>
<p>Ici une bonne résolution serait entre 0.4 et 0.5, nous avons des clusters bien nets, qui ont l’air bien stables.</p>
<p>Pour la suite ““du clustering final”“, nous avons opté pour une résolution de 0.5. Ce choix s’appuie sur la stabilité observée dans l’arbre de clustering (clustree) à ce niveau. Cette résolution permet d’identifier les principales populations cellulaires de manière robuste, tout en conservant la flexibilité nécessaire pour affiner ou ajuster ce paramètre ultérieurement si l’identification de sous-types cellulaires plus précis l’exige.</p>
</section>
<section id="clustering-final" class="level2">
<h2 class="anchored" data-anchor-id="clustering-final">Clustering Final</h2>
<ul>
<li><strong>Calcul des clusters finaux</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">FindNeighbors</span>(seurat_obj_urchin_16f_bis, <span class="at">dims =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">FindClusters</span>(seurat_obj_urchin_16f_bis, <span class="at">resolution =</span> <span class="fl">0.4</span>) <span class="co"># Groupe les cellules par types</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 2500
Number of edges: 80056

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.8133
Number of communities: 6
Elapsed time: 0 seconds</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">RunUMAP</span>(seurat_obj_urchin_16f_bis, <span class="at">dims =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>seurat_obj_urchin_16f_bis <span class="ot">&lt;-</span> <span class="fu">RunTSNE</span>(seurat_obj_urchin_16f_bis, <span class="at">dims =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><strong>Nombre de cellules gardées et médianne :</strong></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># On regarde le nombre de cellules gardées après ce dernier filtrage : </span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>stats_16f_bis_3 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Type de données"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Filtrées optimisées"</span>,</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Nombre de Barcodes"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">ncol</span>(seurat_obj_urchin_16f_bis)),</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Médiane Gènes/Cellule"</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">median</span>(seurat_obj_urchin_16f_bis<span class="sc">$</span>nFeature_RNA) )))</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(stats_16f_bis_3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Type.de.données
                      Filtrées optimisées
Nombre de Barcodes                   2500
Médiane Gènes/Cellule              5785.5</code></pre>
</div>
</div>
</section>
<section id="visualisations-finales" class="level2">
<h2 class="anchored" data-anchor-id="visualisations-finales">Visualisations Finales</h2>
<ul>
<li><strong>UMAP</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">DimPlot</span>(seurat_obj_urchin_16f_bis, <span class="at">reduction =</span> <span class="st">"umap"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"UMAP Finale (Singlets uniquement)16 cell fixées bis"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/umap-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>TSNE</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">DimPlot</span>(seurat_obj_urchin_16f_bis, <span class="at">reduction =</span> <span class="st">"tsne"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">"TSNE Finale (Singlets uniquement)16 cell fixées bis"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/tsne-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="indentifictaion-des-clusters" class="level2">
<h2 class="anchored" data-anchor-id="indentifictaion-des-clusters">Indentifictaion des Clusters</h2>
<ul>
<li><strong>Nombre de gènes par cluster</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(<span class="fu">Idents</span>(seurat_obj_urchin_16f_bis)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1   2   3   4   5 
667 524 474 386 364  85 </code></pre>
</div>
</div>
<ul>
<li><strong>Identification des gènes exprimés</strong> <strong>différentiellement</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identification des gènes marqueurs : Quels gènes sont spécifiques à chaque groupe ?</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>all_markers_16f_bis <span class="ot">&lt;-</span> <span class="fu">FindAllMarkers</span>(seurat_obj_urchin_16f_bis, <span class="at">only.pos =</span> <span class="cn">TRUE</span>, <span class="at">min.pct =</span> <span class="fl">0.25</span>, <span class="at">logfc.threshold =</span> <span class="fl">0.50</span>) <span class="co"># on veut que les gènes surexprimés, présent dans au moins 25% des cellules avec une dif d'expression d'au moins 0,25</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in FindMarkers.default(object = data.use, cells.1 = cells.1, cells.2 =
cells.2, : No features pass logfc.threshold threshold; returning empty
data.frame</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>For a (much!) faster implementation of the Wilcoxon Rank Sum Test,
(default method for FindMarkers) please install the presto package
--------------------------------------------
install.packages('devtools')
devtools::install_github('immunogenomics/presto')
--------------------------------------------
After installation of presto, Seurat will automatically use the more 
efficient implementation (no further action necessary).
This message will be shown once per session</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tableau récapitulatif du nombre de cellules par cluster</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">table</span>(<span class="fu">Idents</span>(seurat_obj_urchin_16f_bis)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1   2   3   4   5 
667 524 474 386 364  85 </code></pre>
</div>
</div>
<ul>
<li><strong>Extraction des gènes marqueurs</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>top40_16f_bis<span class="ot">&lt;-</span> all_markers_16f_bis <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(cluster) <span class="sc">%&gt;%</span> <span class="fu">top_n</span>(<span class="at">n =</span> <span class="dv">40</span>, <span class="at">wt =</span> avg_log2FC)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top40_16f_bis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 200 × 7
# Groups:   cluster [5]
      p_val avg_log2FC pct.1 pct.2 p_val_adj cluster gene      
      &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt; &lt;fct&gt;   &lt;chr&gt;     
 1 1.46e-74      0.975 0.968 0.811  2.58e-70 1       Hook3.1   
 2 2.88e-50      0.810 0.939 0.807  5.10e-46 1       Suvar3-9.1
 3 2.57e-40      1.95  0.38  0.137  4.54e-36 1       SoxE      
 4 1.34e-35      0.797 0.849 0.668  2.36e-31 1       Stx1      
 5 1.63e-32      0.805 0.794 0.619  2.88e-28 1       SPU-017710
 6 2.15e-31      0.799 0.788 0.564  3.80e-27 1       Hnrph2L   
 7 2.94e-31      0.839 0.744 0.525  5.20e-27 1       Rreb1     
 8 3.96e-31      0.786 0.813 0.62   7.01e-27 1       Jip3-1    
 9 2.39e-28      0.841 0.721 0.509  4.22e-24 1       Mrps31L   
10 1.50e-24      0.982 0.574 0.366  2.65e-20 1       Hypp-105  
# ℹ 190 more rows</code></pre>
</div>
</div>
<ul>
<li><strong>Enregistrement des listes des 40 premiers gènes par clusters</strong> :</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définissions du chemin </span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="co">#chemin_bureau &lt;- "~/Desktop/Resultats_Analyse_16_cell_fixees_bis"</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="co">#for (i in 0:6) {</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Filtrer les gènes pour le cluster actuel</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#current_cluster_genes_16f_bis &lt;- all_markers_16f_bis[all_markers_16f_bis$cluster == i, ]</span></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Extraire les 40 meilleurs</span></span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a> <span class="co">#top40_16f_bis &lt;- head(current_cluster_genes_16f_bis, 40)</span></span>
<span id="cb82-12"><a href="#cb82-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb82-13"><a href="#cb82-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Afficher</span></span>
<span id="cb82-14"><a href="#cb82-14" aria-hidden="true" tabindex="-1"></a>  <span class="co">#cat("\n--- Top 40 pour le Cluster", i, "---\n")</span></span>
<span id="cb82-15"><a href="#cb82-15" aria-hidden="true" tabindex="-1"></a>  <span class="co">#print(head(top40_16f_bis, 40)) </span></span>
<span id="cb82-16"><a href="#cb82-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb82-17"><a href="#cb82-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Sauvegarder le fichier CSV </span></span>
<span id="cb82-18"><a href="#cb82-18" aria-hidden="true" tabindex="-1"></a>  <span class="co">#nom_fichier &lt;- paste0(chemin_bureau, "/marqueurs_cluster", i, "_40g.csv")</span></span>
<span id="cb82-19"><a href="#cb82-19" aria-hidden="true" tabindex="-1"></a>  <span class="co">#write.csv(top40_16f_bis, file = nom_fichier, row.names = FALSE)</span></span>
<span id="cb82-20"><a href="#cb82-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb82-21"><a href="#cb82-21" aria-hidden="true" tabindex="-1"></a><span class="co">#}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Pour enregistrer tout ce que j’ai fais :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer le dossier sur le bureau</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="co">#dir.create("~/Desktop/Resultats_Analyse_16_cell_fixees_bis", recursive = TRUE, showWarnings = FALSE)</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Sauvegarder l'objet</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a><span class="co">#saveRDS(seurat_obj_urchin_16f_bis, file = "~/Desktop/Resultats_Analyse_16_cell_fixees_bis/seurat_final.rds")</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Pour tous les gènes ?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Définition du chemin vers ton Bureau</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="co">#chemin_bureau &lt;- "~/Desktop/Resultats_Analyse_16_cell_fixees_bis"</span></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Créer le dossier s'il n'existe pas encore</span></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a><span class="co">#if (!dir.exists(chemin_bureau)) {</span></span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#dir.create(chemin_bureau)</span></span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a><span class="co">#}</span></span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a><span class="co">#for (i in 0:6) {</span></span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 1. Filtrer les gènes spécifiquement pour le cluster i</span></span>
<span id="cb84-12"><a href="#cb84-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># On s'assure que la colonne s'appelle bien 'cluster'</span></span>
<span id="cb84-13"><a href="#cb84-13" aria-hidden="true" tabindex="-1"></a> <span class="co"># current_cluster_genes_16f_bis &lt;- all_markers_16f_bis[all_markers_16f_bis$cluster == i, ]</span></span>
<span id="cb84-14"><a href="#cb84-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb84-15"><a href="#cb84-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 2. Définir le nom du fichier dynamiquement</span></span>
<span id="cb84-16"><a href="#cb84-16" aria-hidden="true" tabindex="-1"></a> <span class="co"># nom_fichier &lt;- paste0(chemin_bureau, "/marqueurs_cluster", i, "_all.csv")</span></span>
<span id="cb84-17"><a href="#cb84-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb84-18"><a href="#cb84-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. SAUVEGARDER l'objet filtré (current_cluster_genes) et non la table entière</span></span>
<span id="cb84-19"><a href="#cb84-19" aria-hidden="true" tabindex="-1"></a>  <span class="co">#write.csv(current_cluster_genes_16f_bis, file = #nom_fichier, row.names = FALSE)</span></span>
<span id="cb84-20"><a href="#cb84-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb84-21"><a href="#cb84-21" aria-hidden="true" tabindex="-1"></a><span class="co">#}</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualiser l'expression du gène sur l'UMAP</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">FeaturePlot</span>(seurat_obj_urchin_16f_bis, <span class="at">features =</span> <span class="st">"Nodal"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pour comparer côte à côte avec les clusters</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">DimPlot</span>(seurat_obj_urchin_16f_bis, <span class="at">reduction =</span> <span class="st">"umap"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">FeaturePlot</span>(seurat_obj_urchin_16f_bis, <span class="at">features =</span> <span class="st">"Nodal"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Trouve les marqueurs pour tous les clusters</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>markers <span class="ot">&lt;-</span> <span class="fu">FindAllMarkers</span>(seurat_obj_urchin_16f_bis, <span class="at">only.pos =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtre pour voir dans quel cluster le gène apparaît</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(markers, gene <span class="sc">==</span> <span class="st">"Nodal"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] p_val      avg_log2FC pct.1      pct.2      p_val_adj  cluster    gene      
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualiser l'expression du gène sur l'UMAP</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">FeaturePlot</span>(seurat_obj_urchin_16f_bis, <span class="at">features =</span> <span class="st">"Pmar1a"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pour comparer côte à côte avec les clusters</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">DimPlot</span>(seurat_obj_urchin_16f_bis, <span class="at">reduction =</span> <span class="st">"umap"</span>, <span class="at">label =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">FeaturePlot</span>(seurat_obj_urchin_16f_bis, <span class="at">features =</span> <span class="st">"Pmar1a"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="sc_16_cell_filtrees_bis_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Trouve les marqueurs pour tous les clusters</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>markers <span class="ot">&lt;-</span> <span class="fu">FindAllMarkers</span>(seurat_obj_urchin_16f_bis, <span class="at">only.pos =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Calculating cluster 5</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtre pour voir dans quel cluster le gène apparaît</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">subset</span>(markers, gene <span class="sc">==</span> <span class="st">"Pmar1a"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] p_val      avg_log2FC pct.1      pct.2      p_val_adj  cluster    gene      
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>